use_frameworks!

target 'LNSideMenu_Example' do
  pod 'LNSideMenu', :path => ‘../‘

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'LNSideMenu_Example'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
